alerts/apps/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('add_task/', views.add_task, name='add_task'),
    path('<int:task_id>/detete_task/', views.delete_task, name='delete_task'),
    path('<int:task_id>/edit_task/', views.edit_task, name='edit_task'),
    ]

alerts/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'notifications'
urlpatterns = [
    path('notifications/', include('notifications.urls')),
    path('admin/', admin.site.urls),
    ]

alerts/apps/notifications/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

class Task(models.Model):

    title = models.CharField('Task title', max_length=100)
    description = models.TextField('Description of title')
    create_datetime = models.DateTimeField('creating date and time')

    
    def __str__(self):
        return self.title

class Notification(models.Model):
    class NotificationUrgency(models.TextChoices):
        MINOR = 'Minor', _('Minor')
        MAJOR = 'Major', _('Major')
        CRITICAL = 'Critical', _('Critical')

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    notification_datetime = models.DateTimeField('notification date and time')
    urgency = models.CharField(max_length=20, 
        choices = NotificationUrgency.choices, 
        default = NotificationUrgency.MINOR, )

alerts/apps/notifications/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseNotFound
from .models import Task, Notification
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse 
from datetime import datetime

from .forms import NotyForm

def index(request):
	task_list = Task.objects.order_by('-create_datetime')
	context = {'task_list': task_list}
	return render(request,'notifications/index.html', context)

def detail(request, task_id):
	task = get_object_or_404(Task, pk=task_id)
	return render(request, 'notifications/detail.html', {'task':task})

def add_task(request):
	a = Task.objects.create(title=request.POST['task_title'], \
		description=request.POST['task_description'], \
		create_datetime=datetime.now())
	date = request.POST['date']
	time = request.POST['time']
	set_datetime = str(date) + ' ' + str(time)
	a.notification_set.create(urgency=request.POST['select_urgency'],\
		notification_datetime=set_datetime)
	return HttpResponseRedirect(reverse('notifications:index'))

def delete_task(request, task_id):
	task = Task.objects.get(pk=task_id)
	task.delete()
	return HttpResponseRedirect(reverse('notifications:index'))
	
def edit_task(request, task_id):
	try:
		task = get_object_or_404(Task, pk=task_id)

		if request.method == "POST":
			task.title = request.POST["task_title"]
			task.description = request.POST["task_description"]
			task.save()
			return render(request, "notifications/detail.html", {'task':task})
		else:
			return render(request, "notifications/edit.html", {'task':task})
	except Task.DoesNotExist:
		return HttpResponseNotFound("<h2>Task not found</h2>")

alerts/apps/notifications/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>	{% block title%} Notify Me! {% endblock %} </title>
</head>

<body>
	{% block content%}{% endblock %}
</body>
</html>

alerts/apps/notifications/templates/notifications/detail.html
{% extends 'base.html' %}

{% block content %}
	
<h1>{{task.title}}</h1>
<p>{{task.description}}</p>
<p>{{task.create_datetime}}</p>

<p>
	<a href="{% url 'notifications:edit_task' task.id %}">Edit</a> | <a href="{% url 'notifications:delete_task' task.id %}">Delete</a>
</p>

<h3>All Notifications</h3>
<ul>
{% for notify in task.notification_set.all %}
<li>{{ notify.notification_datetime }}, {{ notify.urgency }}</li>
{% endfor %}

{% endblock %}

alerts/apps/notifications/templates/notifications/edit.html
{% extends 'base.html' %}

{% block content %}

<h3>Edit your task here </h3>
<form action="{% url 'notifications:edit_task' task.id %}" method="POST">
    {% csrf_token %}
    <p>
        <label>Title: </label><br>
        <input type="text" name="task_title" value="{{task.title}}">
    </p>
    <p>
        <label>Description: </label><br>
        <textarea name="task_description" cols="30" rows ="5">{{task.description}}</textarea><br>
    </p>
    <button type="submit">Send</button>
</form>


{% endblock %}

alerts/apps/notifications/templates/notifications/index.html
<title>Notify Me!</title>

{% block content %}

	<h1>Add you task here</h1>
	<form action="{% url 'notifications:add_task' %}" method="POST">
		{% csrf_token %}
		<p>
			<label for="text">Title: </label><br>
			<input type="text" placeholder="Task title" name="task_title" >
		</p>
		<p>
			<label for="select_urgency">Urgency:</label>
			<select name="select_urgency">
				<option>minor</option>
				<option>major</option>
				<option>critical</option>
			</select>
		</p>
		<p>
			<label for="date">Notification date: </label>
			<input type="date" id="date" name="date"/>
		</p>
		
		<p>
			<label for="time">Time: </label>
        	<input type="time" name="time"/>
		</p>
		<p>
			<label>Description: </label><br>
			<textarea name="task_description" placeholder="Task description" cols="30" rows ="5"></textarea><br>
		</p>
		<button type="submit">Send</button>
	</form>

<h3>Task list</h3>

{% if task_list %}
    <ul>
    {% for a in task_list %}
<!--    <li><a href="/notifications/{{ task.id }}/">{{ task.title }}</a></li> -->
        <li>
        	<a href="{% url 'notifications:detail' a.id %}">{{ a.title }} </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Not available at this moment.</p>
{% endif %}

{% endblock %}